# Generated by Django 2.2.14 on 2020-12-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newsletters',
            new_name='Newsletter',
        ),
    ]
