# Generated by Django 2.2.14 on 2020-12-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20201212_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Contraseña',
            new_name='Contrasena',
        ),
    ]
